"""initial schema

Revision ID: 071cf3eb59d5
Revises: 
Create Date: 2026-09-28 09:36:36.576956
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '071cf3eb59d5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('halls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('layout_width', sa.Integer(), nullable=False),
    sa.Column('layout_height', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_halls_name'), ['name'], unique=True)

    op.create_table('integration_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('exchange_plan', sa.String(length=120), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('org_ref', sa.String(length=64), nullable=False),
    sa.Column('price_type_ref', sa.String(length=64), nullable=False),
    sa.Column('auto_export_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('export_categories', sa.Boolean(), nullable=False),
    sa.Column('export_dishes', sa.Boolean(), nullable=False),
    sa.Column('export_modifiers', sa.Boolean(), nullable=False),
    sa.Column('export_orders', sa.Boolean(), nullable=False),
    sa.Column('export_day_closes', sa.Boolean(), nullable=False),
    sa.Column('last_export_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_in_qr', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_categories_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_categories_slug'), ['slug'], unique=True)

    op.create_table('menu_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), nullable=False),
    sa.Column('show_weights', sa.Boolean(), nullable=False),
    sa.Column('show_calories', sa.Boolean(), nullable=False),
    sa.Column('show_allergens', sa.Boolean(), nullable=False),
    sa.Column('welcome_text', sa.Text(), nullable=False),
    sa.Column('footer_text', sa.Text(), nullable=False),
    sa.Column('theme_color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifier_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onec_inbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onec_inbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onec_inbox_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_onec_inbox_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onec_inbox_processed'), ['processed'], unique=False)

    op.create_table('sync_map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=False
    )
    with op.batch_alter_table('sync_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_map_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_map_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_map_local_id'), ['local_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_manage_menu', sa.Boolean(), nullable=False),
    sa.Column('can_manage_hall', sa.Boolean(), nullable=False),
    sa.Column('can_manage_orders', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('salary_percent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('day_closes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('guests_total', sa.Integer(), nullable=False),
    sa.Column('orders_total', sa.Integer(), nullable=False),
    sa.Column('revenue_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_to_1c', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day_closes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_closes_business_date'), ['business_date'], unique=True)

    op.create_table('dishes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('cooking_minutes', sa.Integer(), nullable=False),
    sa.Column('allergens', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('show_in_qr', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('integration_code', sa.String(length=64), nullable=True),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dishes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishes_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishes_name'), ['name'], unique=False)

    op.create_table('integration_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('entities_total', sa.Integer(), nullable=False),
    sa.Column('entities_success', sa.Integer(), nullable=False),
    sa.Column('entities_error', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_preview', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_delta', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modifiers_group_id'), ['group_id'], unique=False)

    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hall_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('qr_token', sa.String(length=48), nullable=False),
    sa.Column('qr_regenerated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_hall_id'), ['hall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_qr_token'), ['qr_token'], unique=True)

    op.create_table('dish_modifier_groups',
    sa.Column('dish_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'group_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_reserved_at'), ['reserved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_table_id'), ['table_id'], unique=False)

    op.create_table('table_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('opened_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_minutes', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_sessions_table_id'), ['table_id'], unique=False)

    op.create_table('occupancy_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['table_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_events_table_id'), ['table_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('table_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('guest_comment', sa.Text(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('exported_to_1c', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_session_id'], ['table_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_session_id'), ['table_session_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=True),
    sa.Column('dish_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('cooking_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_modifiers_order_item_id'), ['order_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_modifiers_order_item_id'))

    op.drop_table('order_item_modifiers')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_dish_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_table_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_table_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_external_id'))

    op.drop_table('orders')
    with op.batch_alter_table('occupancy_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_events_table_id'))

    op.drop_table('occupancy_events')
    with op.batch_alter_table('table_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_sessions_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_sessions_status'))

    op.drop_table('table_sessions')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_table_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_reservations_reserved_at'))

    op.drop_table('reservations')
    op.drop_table('dish_modifier_groups')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_qr_token'))
        batch_op.drop_index(batch_op.f('ix_tables_name'))
        batch_op.drop_index(batch_op.f('ix_tables_hall_id'))
        batch_op.drop_index(batch_op.f('ix_tables_external_id'))

    op.drop_table('tables')
    with op.batch_alter_table('modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modifiers_group_id'))

    op.drop_table('modifiers')
    op.drop_table('integration_logs')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishes_name'))
        batch_op.drop_index(batch_op.f('ix_dishes_external_id'))
        batch_op.drop_index(batch_op.f('ix_dishes_category_id'))

    op.drop_table('dishes')
    with op.batch_alter_table('day_closes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_closes_business_date'))

    op.drop_table('day_closes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('sync_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_map_local_id'))
        batch_op.drop_index(batch_op.f('ix_sync_map_external_id'))
        batch_op.drop_index(batch_op.f('ix_sync_map_entity_type'))

    op.drop_table('sync_map')
    with op.batch_alter_table('onec_inbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onec_inbox_processed'))
        batch_op.drop_index(batch_op.f('ix_onec_inbox_external_id'))
        batch_op.drop_index(batch_op.f('ix_onec_inbox_entity_type'))

    op.drop_table('onec_inbox')
    op.drop_table('modifier_groups')
    op.drop_table('menu_settings')
    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_menu_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_menu_categories_name'))
        batch_op.drop_index(batch_op.f('ix_menu_categories_external_id'))

    op.drop_table('menu_categories')
    op.drop_table('integration_settings')
    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_halls_name'))

    op.drop_table('halls')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
