"""sync_map unique refs

Revision ID: 3cd448ea3044
Revises: 071cf3eb59d5
Create Date: 2026-09-28 10:12:19.329670
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3cd448ea3044'
down_revision: str | None = '071cf3eb59d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _dedupe(columns: list[str]) -> None:
    """Delete duplicate sync_map rows, keeping one per (entity_type, <column>).

    Done through the ORM table rather than raw SQL: PostgreSQL has no
    min()/max() for uuid, so the obvious ``DELETE ... WHERE id NOT IN
    (SELECT MIN(id) ...)`` works on SQLite but aborts the whole migration on
    Postgres. Going via the model also keeps the uuid bind values correct on
    both backends.
    """
    from app.models.integration import SyncMap

    session = sa.orm.Session(bind=op.get_bind())
    try:
        rows = session.execute(sa.select(SyncMap)).scalars().all()
        # prefer the row that actually carries sync data, then a stable order
        rows.sort(key=lambda r: (r.last_synced_at is None, r.content_hash is None, str(r.id)))

        seen: set[tuple[str, str]] = set()
        doomed: list[object] = []
        for row in rows:
            for column in columns:
                key = (row.entity_type, getattr(row, column))
                if key in seen:
                    doomed.append(row.id)
                    break
                seen.add(key)
        if doomed:
            session.execute(sa.delete(SyncMap).where(SyncMap.id.in_(doomed)))
            session.commit()
    finally:
        session.close()


def upgrade() -> None:
    # older dev databases may contain duplicate refs (created before _ref()
    # flushed its inserts)
    _dedupe(["local_id"])
    _dedupe(["external_id"])

    with op.batch_alter_table('dish_modifier_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_modifier_groups_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dish_modifier_groups_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('sync_map', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sync_map_entity_local', ['entity_type', 'local_id'])
        batch_op.create_unique_constraint('uq_sync_map_entity_external', ['entity_type', 'external_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_map', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sync_map_entity_local', type_='unique')
        batch_op.drop_constraint('uq_sync_map_entity_external', type_='unique')

    with op.batch_alter_table('dish_modifier_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_modifier_groups_group_id'))
        batch_op.drop_index(batch_op.f('ix_dish_modifier_groups_dish_id'))

    # ### end Alembic commands ###
